### ISSUE TITLE
example_interactive.ipynb  3. Predict P/S-phase picks using PhaseNet seems does not work

### ISSUE THREAD

**Issue by IsanaYashiro** [wayneweiqiang/PhaseNet#46]
when i run this part, the result is <Response [500]>

```
req = {"id": [data_id],
       "timestamp": [timestamp],
       "vec": [data.tolist()]}
resp = requests.post(f'{PHASENET_API_URL}/predict', json=req)
print(resp)
# print('Picks', resp.json())
```
something wrong happened in requests.post

**Comment by wayneweiqiang** [comment]
Hi, "Response [500]" usually means the data format is wrong. Are you running the default notebook or using your own data. I can run the default notebook on my laptop.

**Comment by IsanaYashiro** [comment]
Thank you for your help, Dr. Zhu.&nbsp;Maybe my conda env&nbsp;did&nbsp;not set&nbsp;up




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wayneweiqiang/PhaseNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 凌晨4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wayneweiqiang/PhaseNet] example_interactive.ipynb  3. Predict P/S-phase picks using PhaseNet seems does not work (Issue #46)





 
Hi, "Response [500]" usually means the data format is wrong. Are you running the default notebook or using your own data. I can run the default notebook on my laptop.

**Comment by coralkchen** [comment]
Hi, I've also run into issues when running the default notebook.

I'm getting a "Response [502]" when running on the Quakeflow API, along with this error:
`JSONDecodeError: Expecting value: line 2 column 1 (char 1)`

When running on my local machine, the program is unable to establish a connection with my port and throws this error:
`HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc006c21a50>: Failed to establish a new connection: [Errno 61] Connection refused'))`

I was able to run the demo notebook on a version of PhaseNet downloaded onto a different Mac early in the year. Any insight would be greatly appreciated.

Thanks!

**Comment by wayneweiqiang** [comment]
My server seems to be dead. I have restarted the server. It should work now.

**Comment by coralkchen** [comment]
Thanks for the response. Running with the Quakeflow API works now, though I still can't connect to my local port.
